spring.application.name=team

spring.datasource.url=jdbc:postgresql://localhost:5432/sampleoltpdata
spring.datasource.username=postgres
spring.datasource.password=${dbpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# Recommended for Hibernate & PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8081


