from pathlib import Path
import random
import re
from datetime import datetime, timedelta

# Read user_ids from users_insert.sql
users_file = Path(__file__).parent / "users_insert.sql"
user_ids = []
with open(users_file, "r") as f:
    for line in f:
        match = re.search(r"VALUES \((\d+),", line)
        if match:
            user_ids.append(int(match.group(1)))

# Read user_roles_insert.sql to identify CLIENT users
user_roles_file = Path(__file__).parent / "user_roles_insert.sql"
client_user_ids = set()
with open(user_roles_file, "r") as f:
    for line in f:
        # Parse lines like: INSERT INTO User_Roles (user_id, role_id) VALUES (1, 1);
        match = re.search(r"VALUES \((\d+), (\d+)\)", line)
        if match:
            user_id = int(match.group(1))
            role_id = int(match.group(2))
            # role_id=1 is CLIENT (first role from roles_insert.sql)
            if role_id == 1:
                client_user_ids.add(user_id)

if not client_user_ids:
    print("Error: Could not identify CLIENT users from user_roles_insert.sql")
    exit(1)

# Generate accounts
accounts = []
account_id = 1
base_date = datetime(2024, 1, 1)

for user_id in sorted(client_user_ids):
    # Generate 1-4 active accounts per client user
    num_active_accounts = random.randint(1, 4)
    
    for _ in range(num_active_accounts):
        created_date = base_date + timedelta(days=random.randint(0, 600))
        updated_date = created_date + timedelta(days=random.randint(0, 200))
        
        # Status distribution: 96% ACTIVE, 3% SUSPENDED, 1% PENDING
        status_rand = random.random()
        if status_rand < 0.96:
            status = "ACTIVE"
        elif status_rand < 0.99:
            status = "SUSPENDED"
        else:
            status = "PENDING"
        
        accounts.append({
            "account_id": account_id,
            "user_id": user_id,
            "created_date": created_date,
            "updated_date": updated_date,
            "status": status
        })
        account_id += 1
    
    # Generate 0-2 closed accounts per client user (most should have 0)
    num_closed_accounts = random.choices([0, 1, 2], weights=[85, 10, 5])[0]
    
    for _ in range(num_closed_accounts):
        created_date = base_date + timedelta(days=random.randint(0, 600))
        updated_date = created_date + timedelta(days=random.randint(50, 300))
        
        accounts.append({
            "account_id": account_id,
            "user_id": user_id,
            "created_date": created_date,
            "updated_date": updated_date,
            "status": "CLOSED"
        })
        account_id += 1

# Write to SQL file
output_path = Path(__file__).parent / "accounts_insert.sql"
with open(output_path, "w") as f:
    f.write("-- Accounts generated by accounts_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Accounts table\n")
    f.write("-- Table: Accounts (Account_ID, User_ID, Created_Date, Updated_Date, Status)\n")
    f.write("-- Status options: PENDING, ACTIVE, SUSPENDED, CLOSED\n")
    f.write("-- Active accounts: ~96% ACTIVE, ~3% SUSPENDED, ~1% PENDING\n\n")
    
    for account in accounts:
        f.write(
            f"INSERT INTO Accounts (Account_ID, User_ID, Created_Date, Updated_Date, Status) "
            f"VALUES ({account['account_id']}, {account['user_id']}, "
            f"'{account['created_date'].strftime('%Y-%m-%d %H:%M:%S')}', "
            f"'{account['updated_date'].strftime('%Y-%m-%d %H:%M:%S')}', "
            f"'{account['status']}');\n"
        )

# Calculate statistics
active_count = sum(1 for a in accounts if a['status'] == 'ACTIVE')
suspended_count = sum(1 for a in accounts if a['status'] == 'SUSPENDED')
pending_count = sum(1 for a in accounts if a['status'] == 'PENDING')
closed_count = sum(1 for a in accounts if a['status'] == 'CLOSED')

print(f"Generated accounts for CLIENT users:")
print(f"- Total CLIENT users: {len(client_user_ids)}")
print(f"- Total accounts generated: {len(accounts)}")
print(f"- ACTIVE: {active_count} ({active_count/len(accounts)*100:.1f}%)")
print(f"- SUSPENDED: {suspended_count} ({suspended_count/len(accounts)*100:.1f}%)")
print(f"- PENDING: {pending_count} ({pending_count/len(accounts)*100:.1f}%)")
print(f"- CLOSED: {closed_count} ({closed_count/len(accounts)*100:.1f}%)")
print(f"- Saved to {output_path}")