#!/usr/bin/env python3
"""
account_cash_balances_generator.py - Generate account cash balance data.

The Account_Cash_Balances table tracks current cash position for each account.
- Cash_Balance: Current cash available in the account (including deposits, withdrawals, trades)
- Updated_At: Timestamp of last balance update

Balances are calculated from:
1. Initial deposits (from Transactions)
2. Subsequent deposits/withdrawals
3. Trade settlements (buy/sell from Cash_Ledger)
4. Dividends, interest, fees
"""

from pathlib import Path
import random
import re
from datetime import datetime, timedelta

# Read account_ids from accounts_insert.sql
data_folder = Path(__file__).parent.parent / "data"
accounts_file = data_folder / "accounts_insert.sql"
account_data = {}  # account_id -> created_date

if not accounts_file.exists():
    print(f"Error: Could not find {accounts_file}")
    exit(1)

with open(accounts_file, "r") as f:
    for line in f:
        # Expected format: INSERT INTO Accounts (Account_ID, User_ID, Created_Date) 
        # VALUES (1, 501, '2025-01-15 08:30:45');
        match = re.search(
            r"VALUES \((\d+),\s*(\d+),\s*'([^']+)'\)",
            line
        )
        if match:
            account_id = int(match.group(1))
            user_id = int(match.group(2))
            created_date = match.group(3)
            account_data[account_id] = created_date

if not account_data:
    print(f"Error: Could not parse accounts from {accounts_file}")
    exit(1)

# Generate cash balances for each account
output_path = data_folder / "account_cash_balances_insert.sql"

with open(output_path, "w") as f:
    f.write("-- Account cash balances generated by account_cash_balances_generator.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Account_Cash_Balances table\n")
    f.write("-- Cash_Balance represents current available cash in the account\n\n")
    
    for account_id in sorted(account_data.keys()):
        created_date_str = account_data[account_id]
        
        # Generate starting balance: $50K-$1M for typical accounts
        # This represents initial deposits + cumulative trading activity
        cash_balance = random.uniform(50000, 1000000)
        
        # Format with 2 decimal places
        cash_balance_fmt = f"{cash_balance:.2f}"
        
        # Updated_At is set to now (or close to current time)
        updated_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        f.write(
            f"INSERT INTO Account_Cash_Balances (Account_ID, Cash_Balance, Updated_At) "
            f"VALUES ({account_id}, {cash_balance_fmt}, '{updated_at}');\n"
        )

print("Generated account cash balances:")
print(f"- Created balance records for {len(account_data)} accounts")
print(f"- Cash_Balance range: $50K - $1M per account")
print(f"- Saved to {output_path}")
print(f"- Note: Run AFTER accounts_generation.py and BEFORE transactions/trades")

