from pathlib import Path
import random
import re
from datetime import datetime, timedelta

# Read users from users_insert.sql to identify CLIENT users (role_id=1)
users_file = Path(__file__).parent / "users_insert.sql"
client_user_ids = []

with open(users_file, "r") as f:
    for line in f:
        # Parse: INSERT INTO Users (...) VALUES (user_id, 'name', 'email', 'password_hash', 'created_date', 'status', role_id)
        match = re.search(r"VALUES \((\d+),.*?, (\d+)\);", line)
        if match:
            user_id = int(match.group(1))
            role_id = int(match.group(2))
            # Only create accounts for CLIENT users (role_id=1)
            if role_id == 1:
                client_user_ids.append(user_id)

if not client_user_ids:
    print("Error: Could not identify CLIENT users from users_insert.sql")
    exit(1)

# Generate accounts
accounts = []
account_id = 1
base_date = datetime(2024, 1, 1)

for user_id in sorted(client_user_ids):
    # Generate 1-4 accounts per client user
    num_accounts = random.randint(1, 4)
    
    for _ in range(num_accounts):
        created_date = base_date + timedelta(days=random.randint(0, 600))
        
        accounts.append({
            "account_id": account_id,
            "user_id": user_id,
            "created_date": created_date
        })
        account_id += 1

# Write to SQL file
output_path = Path(__file__).parent / "accounts_insert.sql"
with open(output_path, "w") as f:
    f.write("-- Accounts generated by accounts_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Accounts table\n")
    f.write("-- Table: Accounts (Account_ID, User_ID, Created_Date)\n")
    f.write(f"-- Total accounts: {len(accounts)} (~{len(accounts)/len(client_user_ids):.1f} per client user)\n\n")
    
    for account in accounts:
        f.write(
            f"INSERT INTO Accounts (Account_ID, User_ID, Created_Date) "
            f"VALUES ({account['account_id']}, {account['user_id']}, "
            f"'{account['created_date'].strftime('%Y-%m-%d %H:%M:%S')}');\n"
        )

print(f"Generated {len(accounts)} accounts for {len(client_user_ids)} CLIENT users")
print(f"Average accounts per user: {len(accounts)/len(client_user_ids):.2f}")
print(f"Saved to {output_path}")