#!/usr/bin/env python3
"""
buying_power_generator.py - Generate account buying power data.

The Buying_Power table tracks capital allocation for each account:
- Account_Value: Total liquid cash (Buying_Power + Reserved_Cash)
- Buying_Power: Available cash for new orders (Account_Value - Reserved_Cash)
- Reserved_Cash: Cash held for pending orders (especially after-hours)

When an order is placed:
- Buying_Power decreases (cash locked for the order)
- Reserved_Cash increases (by same amount)
- Account_Value remains unchanged (sum of Buying_Power + Reserved_Cash)
"""

from pathlib import Path
import random
import re

# Read account_ids from accounts_insert.sql
accounts_file = Path(__file__).parent / "accounts_insert.sql"
account_data = {}  # account_id -> (user_id, created_date, status)

if not accounts_file.exists():
    print(f"Error: Could not find {accounts_file}")
    exit(1)

with open(accounts_file, "r") as f:
    for line in f:
        # Expected format: INSERT INTO Accounts (Account_ID, User_ID, Created_Date, Status) 
        # VALUES (1, 501, '2025-01-15 08:30:45', 'ACTIVE');
        match = re.search(
            r"VALUES \((\d+),\s*(\d+),\s*'([^']+)',\s*'([^']+)'\)",
            line
        )
        if match:
            account_id = int(match.group(1))
            user_id = int(match.group(2))
            created_date = match.group(3)
            status = match.group(4)
            account_data[account_id] = (user_id, created_date, status)

if not account_data:
    print(f"Error: Could not parse accounts from {accounts_file}")
    exit(1)

num_accounts = len(account_data)

# Generate buying power for each account
output_path = Path(__file__).parent / "buying_power_insert.sql"

with open(output_path, "w") as f:
    f.write("-- Account buying power data generated by buying_power_generator.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Buying_Power table\n")
    f.write("-- Account_Value = Buying_Power + Reserved_Cash\n\n")
    
    for account_id in sorted(account_data.keys()):
        user_id, created_date, status = account_data[account_id]
        
        # Generate account value (total liquid cash): $10K to $1M
        # Active accounts tend to have more cash than suspended accounts
        if status == "ACTIVE":
            account_value = random.uniform(50000, 1000000)
        else:
            account_value = random.uniform(10000, 100000)
        
        # Generate reserved cash: typically 0-30% of account value for pending orders
        reserved_cash = random.uniform(0, account_value * 0.30)
        
        # Buying power = account_value - reserved
        buying_power = account_value - reserved_cash
        
        # Format with 2 decimal places
        account_value_fmt = f"{account_value:.2f}"
        reserved_cash_fmt = f"{reserved_cash:.2f}"
        buying_power_fmt = f"{buying_power:.2f}"
        
        f.write(
            f"INSERT INTO Buying_Power (Account_ID, Account_Value, Reserved_Cash, Buying_Power, Last_Updated) "
            f"VALUES ({account_id}, {account_value_fmt}, {reserved_cash_fmt}, {buying_power_fmt}, CURRENT_TIMESTAMP);\n"
        )

print("Generated account buying power data:")
print(f"- Created buying power records for {num_accounts} accounts")
print(f"- Account_Value range: $10K - $1M (based on account status)")
print(f"- Reserved_Cash: 0-30% of account value for pending orders")
print(f"- Buying_Power: Account_Value - Reserved_Cash")
print(f"- Saved to {output_path}")
print(f"- Note: Run AFTER accounts_generation.py")
