#!/usr/bin/env python3
"""
buying_power_generator.py - Generate account buying power (available cash) data.

The Buying_Power table tracks the available capital for each account:
- Available_Cash: Actual liquid cash in the account
- Reserved_Cash: Cash held for pending orders (especially after-hours)
- Buying_Power: Available_Cash - Reserved_Cash (actual available for trading)

This generator creates initial buying power data for each account.
"""

from pathlib import Path
import random
import re

# Read account_ids from accounts_insert.sql
accounts_file = Path(__file__).parent / "accounts_insert.sql"
account_data = {}  # account_id -> (user_id, created_date, status)

if not accounts_file.exists():
    print(f"Error: Could not find {accounts_file}")
    exit(1)

with open(accounts_file, "r") as f:
    for line in f:
        # Expected format: INSERT INTO Accounts (Account_ID, User_ID, Created_Date, Status) 
        # VALUES (1, 501, '2025-01-15 08:30:45', 'ACTIVE');
        match = re.search(
            r"VALUES \((\d+),\s*(\d+),\s*'([^']+)',\s*'([^']+)'\)",
            line
        )
        if match:
            account_id = int(match.group(1))
            user_id = int(match.group(2))
            created_date = match.group(3)
            status = match.group(4)
            account_data[account_id] = (user_id, created_date, status)

if not account_data:
    print(f"Error: Could not parse accounts from {accounts_file}")
    exit(1)

num_accounts = len(account_data)

# Generate buying power for each account
output_path = Path(__file__).parent / "buying_power_insert.sql"

with open(output_path, "w") as f:
    f.write("-- Account buying power data generated by buying_power_generator.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Buying_Power table\n")
    f.write("-- Buying_Power = Available_Cash - Reserved_Cash\n\n")
    
    for account_id in sorted(account_data.keys()):
        user_id, created_date, status = account_data[account_id]
        
        # Generate available cash: ranges from $10K to $1M
        # Active accounts tend to have more cash than suspended accounts
        if status == "ACTIVE":
            available_cash = random.uniform(50000, 1000000)
        else:
            available_cash = random.uniform(10000, 100000)
        
        # Generate reserved cash: typically 0-30% of available cash for pending orders
        reserved_cash = random.uniform(0, available_cash * 0.30)
        
        # Buying power = available - reserved
        buying_power = available_cash - reserved_cash
        
        # Format with 2 decimal places
        available_cash_fmt = f"{available_cash:.2f}"
        reserved_cash_fmt = f"{reserved_cash:.2f}"
        buying_power_fmt = f"{buying_power:.2f}"
        
        f.write(
            f"INSERT INTO Buying_Power (Account_ID, Available_Cash, Reserved_Cash, Buying_Power, Last_Updated) "
            f"VALUES ({account_id}, {available_cash_fmt}, {reserved_cash_fmt}, {buying_power_fmt}, CURRENT_TIMESTAMP);\n"
        )

print("Generated account buying power data:")
print(f"- Created buying power records for {num_accounts} accounts")
print(f"- Available_Cash range: $10K - $1M (based on account status)")
print(f"- Reserved_Cash: 0-30% of available cash for pending orders")
print(f"- Buying_Power: Available_Cash - Reserved_Cash")
print(f"- Saved to {output_path}")
print(f"- Note: Run AFTER accounts_generation.py")
