#!/usr/bin/env python3
"""
order_reservations_generator.py - Generate order reservation records.

The Order_Reservations table tracks cash/share reservations for each order:
- For BUY orders: Reserved_Cash = cash held for the purchase (from Requested_Amount)
- For SELL orders: Reserved_Quantity = shares held for the sale (from Quantity_Ordered)
- Status: ACTIVE (order pending), CONSUMED (order filled), RELEASED (order rejected/cancelled)

Reservations ensure that:
1. Account has sufficient funds/shares before execution
2. Reserved resources are locked until order resolves
3. Reversal/cancellation releases reserved resources
"""

from pathlib import Path
import re
import uuid
from datetime import datetime

# Read orders from orders_insert.sql
orders_file = Path(__file__).parent / "orders_insert.sql"
orders = []

if not orders_file.exists():
    print(f"Error: Could not find {orders_file}")
    exit(1)

with open(orders_file, "r") as f:
    for line in f:
        # Parse: INSERT INTO Orders (Order_ID, Account_ID, Security_ID, Client_Request_ID, Side, 
        #                             Requested_Amount, Quantity_Ordered, Order_Status, Created_Date, Updated_Date, 
        #                             Accepted_At, Terminal_At, Rejection_Reason)
        # VALUES (order_id, account_id, security_id, 'uuid', 'B'/'S', requested_amount/NULL, quantity/NULL, 'status', 'created_date', 'updated_date', ...)
        
        match = re.search(
            r"VALUES \((\d+),\s*(\d+),\s*(\d+),\s*'([^']+)',\s*'([BS])',\s*([^,]*),\s*([^,]*),\s*'([^']*)',",
            line
        )
        if match:
            order_id = int(match.group(1))
            account_id = int(match.group(2))
            security_id = int(match.group(3))
            client_request_id = match.group(4)
            side = match.group(5)  # 'B' or 'S'
            requested_amount = match.group(6).strip()  # For BUY
            quantity_ordered = match.group(7).strip()  # For SELL
            order_status = match.group(8)
            
            # For BUY: use Requested_Amount; for SELL: use Quantity_Ordered
            if side == 'B':
                try:
                    reserved_value = float(requested_amount)
                except (ValueError, TypeError):
                    continue
                reserved_quantity = None
            else:  # 'S'
                try:
                    reserved_value = float(quantity_ordered)
                except (ValueError, TypeError):
                    continue
                reserved_quantity = None
            
            # Determine reservation status based on order status
            if order_status in ('SUBMITTED', 'ACCEPTED', 'IN_EXECUTION'):
                res_status = 'ACTIVE'
                resolved_at = None
            elif order_status == 'FILLED':
                res_status = 'CONSUMED'
                resolved_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            else:  # REJECTED, CANCELLED
                res_status = 'RELEASED'
                resolved_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            
            orders.append({
                'order_id': order_id,
                'account_id': account_id,
                'security_id': security_id,
                'side': side,
                'reserved_value': reserved_value,
                'reserved_quantity': reserved_quantity,
                'status': res_status,
                'resolved_at': resolved_at,
                'order_status': order_status
            })

if not orders:
    print(f"Error: Could not parse orders from {orders_file}")
    exit(1)

# Generate order reservations
output_path = Path(__file__).parent / "order_reservations_insert.sql"

with open(output_path, "w") as f:
    f.write("-- Order reservations generated by order_reservations_generator.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Order_Reservations table\n")
    f.write("-- BUY orders: Reserve cash (Requested_Amount)\n")
    f.write("-- SELL orders: Reserve quantity (Quantity_Ordered)\n\n")
    
    for order in orders:
        side = order['side']
        
        if side == 'B':
            # BUY: Reserved_Cash = Requested_Amount, Reserved_Quantity = NULL
            reserved_cash = f"{order['reserved_value']:.2f}"
            reserved_quantity = "NULL"
        else:
            # SELL: Reserved_Quantity = Quantity_Ordered, Reserved_Cash = NULL
            reserved_cash = "NULL"
            reserved_quantity = f"{order['reserved_value']:.12f}"
        
        resolved_at_str = f"'{order['resolved_at']}'" if order['resolved_at'] else "NULL"
        
        f.write(
            f"INSERT INTO Order_Reservations (Order_ID, Account_ID, Security_ID, Side, "
            f"Reserved_Cash, Reserved_Quantity, Status, Created_Date, Resolved_At) "
            f"VALUES ({order['order_id']}, {order['account_id']}, {order['security_id']}, '{side}', "
            f"{reserved_cash}, {reserved_quantity}, '{order['status']}', CURRENT_TIMESTAMP, {resolved_at_str});\n"
        )

print("Generated order reservations:")
print(f"- Created {len(orders)} reservation records")
buy_count = sum(1 for o in orders if o['side'] == 'B')
sell_count = sum(1 for o in orders if o['side'] == 'S')
print(f"  * {buy_count} BUY orders (reserve cash)")
print(f"  * {sell_count} SELL orders (reserve quantity)")
active_count = sum(1 for o in orders if o['status'] == 'ACTIVE')
consumed_count = sum(1 for o in orders if o['status'] == 'CONSUMED')
released_count = sum(1 for o in orders if o['status'] == 'RELEASED')
print(f"  * {active_count} ACTIVE reservations")
print(f"  * {consumed_count} CONSUMED reservations")
print(f"  * {released_count} RELEASED reservations")
print(f"- Saved to {output_path}")
print(f"- Note: Run AFTER orders_generation.py")
