#!/usr/bin/env python3
"""
roles_generation.py - Generate static roles reference data for User_Roles mapping.

The Roles table is a static reference table with two standard roles:
1. CLIENT (role_id=1) - Standard user role
2. ADMIN (role_id=2) - Administrator role

This generator produces the initial roles data that is referenced by user_roles_generation.py.
"""

from pathlib import Path

# Define the standard roles for the PaySprint Wealth Platform
ROLES = [
    (1, "CLIENT"),   # Standard user role for clients
    (2, "ADMIN"),    # Administrator role for platform admins
]

data_folder = Path(__file__).parent.parent / "data"
output_path = data_folder / "roles_insert.sql"

with open(output_path, "w") as f:
    f.write("-- Roles reference data generated by roles_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Roles table\n")
    f.write("-- These are static reference roles used by the platform\n\n")
    
    for role_id, role_name in ROLES:
        f.write(f"INSERT INTO Roles (Role_ID, Name) VALUES ({role_id}, '{role_name}');\n")

print("Generated roles reference data:")
print(f"- Created {len(ROLES)} standard roles:")
for role_id, role_name in ROLES:
    print(f"  * Role_ID {role_id}: {role_name}")
print(f"- Saved to {output_path}")
print(f"- Note: This must be run BEFORE user_roles_generation.py")

