import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path

# Set random seed for reproducibility
np.random.seed(42)

# Define parameters
SECTORS = [
    'Technology', 'Healthcare', 'Financials', 'Energy', 'Consumer Discretionary',
    'Consumer Staples', 'Industrials', 'Materials', 'Real Estate', 'Utilities',
    'Communication Services', 'Information Technology'
]

ASSET_TYPES = ['STOCK', 'BOND', 'ETF', 'CRYPTO']
STATUSES = ['ACTIVE', 'HALTED', 'DELISTED']

# Asset type distribution: 80% STOCK, 10% BOND, 7% ETF, 3% CRYPTO
asset_type_weights = [0.80, 0.10, 0.07, 0.03]

# Status distribution: 95% ACTIVE, 4% HALTED, 1% DELISTED
status_weights = [0.95, 0.04, 0.01]

def generate_ticker(exchange, index):
    """Generate a fake ticker symbol"""
    vowels = 'AEIOU'
    consonants = 'BCDFGHJKLMNPQRSTVWXYZ'
    
    # Create variety in ticker lengths (2-5 characters)
    length = np.random.choice([2, 3, 4, 5], p=[0.1, 0.4, 0.35, 0.15])
    ticker = ''.join(np.random.choice(list(consonants + vowels), length))
    
    return ticker.upper()

def generate_securities(exchange, count):
    """Generate fake securities for an exchange"""
    securities = []
    
    for i in range(count):
        ticker = generate_ticker(exchange, i)
        
        # Ensure unique tickers
        while any(s['Ticker'] == ticker for s in securities):
            ticker = generate_ticker(exchange, i)
        
        security = {
            'Ticker': ticker,
            'Exchange': exchange,
            'Name': f"{ticker} Corporation",
            'Asset_Type': np.random.choice(ASSET_TYPES, p=asset_type_weights),
            'Status': np.random.choice(STATUSES, p=status_weights),
            'Sector': np.random.choice(SECTORS)
        }
        
        securities.append(security)
    
    return securities

# Generate securities for both exchanges
print("Generating NYSE securities...")
nyse_securities = generate_securities('NYSE', 500)

print("Generating NASDAQ securities...")
nasdaq_securities = generate_securities('NASDAQ', 500)

# Combine all securities
all_securities = nyse_securities + nasdaq_securities

# Create DataFrame
df = pd.DataFrame(all_securities)

# Verify distributions
print("\n" + "="*70)
print("VERIFICATION OF DISTRIBUTIONS")
print("="*70)

print("\n1. ASSET TYPE DISTRIBUTION (Target: 80% STOCK, 10% BOND, 7% ETF, 3% CRYPTO):")
asset_dist = df['Asset_Type'].value_counts(normalize=True).sort_index()
for asset_type, pct in asset_dist.items():
    print(f"   {asset_type}: {pct*100:.2f}% ({int(pct*1000)} securities)")

print("\n2. STATUS DISTRIBUTION (Target: 95% ACTIVE, 4% HALTED, 1% DELISTED):")
status_dist = df['Status'].value_counts(normalize=True).sort_index()
for status, pct in status_dist.items():
    print(f"   {status}: {pct*100:.2f}% ({int(pct*1000)} securities)")

print("\n3. EXCHANGE DISTRIBUTION:")
exchange_dist = df['Exchange'].value_counts()
for exchange, count in exchange_dist.items():
    print(f"   {exchange}: {count} securities")

print("\n4. SECTOR DISTRIBUTION:")
sector_dist = df['Sector'].value_counts().sort_values(ascending=False)
for sector, count in sector_dist.items():
    print(f"   {sector}: {count} securities ({count/1000*100:.1f}%)")

print("\n5. SAMPLE SECURITIES:")
print(df.head(10).to_string())

# Generate SQL INSERT statements
def generate_sql_inserts(dataframe, table_name='Securities'):
    """Generate SQL INSERT statements from DataFrame"""
    sql_statements = []
    
    # Add header comment
    sql_statements.append("-- Securities generated by securities_generation.py")
    sql_statements.append("-- Execute this file in PostgreSQL to populate the Securities table")
    sql_statements.append(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    sql_statements.append(f"-- Total records: {len(dataframe)}")
    sql_statements.append("-- Table: Securities (Security_ID, Ticker, Name, Asset_Type, Exchange, Status, Sector)\n")
    
    for idx, row in dataframe.iterrows():
        security_id = idx + 1
        # Escape single quotes in names
        name = row['Name'].replace("'", "''")
        sector = row['Sector'].replace("'", "''")
        
        insert_statement = (
            f"INSERT INTO Securities (Security_ID, Ticker, Name, Asset_Type, Exchange, Status, Sector) "
            f"VALUES ({security_id}, '{row['Ticker']}', '{name}', '{row['Asset_Type']}', '{row['Exchange']}', '{row['Status']}', '{sector}');"
        )
        sql_statements.append(insert_statement)
    
    return '\n'.join(sql_statements)

# Save to SQL file
output_path = Path(__file__).parent / 'securities_insert.sql'
sql_content = generate_sql_inserts(df)

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(sql_content)

print(f"\n\n✓ Successfully generated 1000 fake securities!")
print(f"✓ Saved to: {output_path}")

# Display summary statistics
print("\n" + "="*70)
print("SUMMARY STATISTICS")
print("="*70)
print(f"Total Securities: {len(df)}")
print(f"NYSE Securities: {len(df[df['Exchange'] == 'NYSE'])}")
print(f"NASDAQ Securities: {len(df[df['Exchange'] == 'NASDAQ'])}")

# Show sample SQL statements
print("\n" + "="*70)
print("SAMPLE SQL STATEMENTS (first 5)")
print("="*70)
lines = sql_content.split('\n')
for line in lines[:10]:
    print(line)