import random
import re
from datetime import datetime, timedelta

def parse_executions_file(filepath):
    """Parse executions_insert.sql to extract settled executions"""
    executions = []
    
    try:
        with open(filepath, 'r') as f:
            content = f.read()
        
        # Pattern to extract execution data from INSERT statement
        # VALUES (execution_id, order_id, quantity_filled, price_of_execution, 'time_of_execution', 'date_of_settlement', 'status_of_settlement', 'exchange_trade_id')
        pattern = r"VALUES\s*\((\d+),\s*(\d+),\s*(\d+),\s*([^,]*),\s*'([^']*)',\s*'([^']*)',\s*'([^']*)',\s*'([^']*)'\s*\)"
        
        matches = re.findall(pattern, content)
        for match in matches:
            execution_id, order_id, quantity_filled, price_str, time_of_execution, date_of_settlement, status_of_settlement, exchange_trade_id = match
            
            # Only include SETTLED executions
            if status_of_settlement == 'SETTLED':
                try:
                    price = float(price_str)
                except ValueError:
                    price = 0.0
                
                executions.append({
                    'execution_id': int(execution_id),
                    'order_id': int(order_id),
                    'quantity_filled': int(quantity_filled),
                    'price_of_execution': price,
                    'time_of_execution': time_of_execution,
                    'date_of_settlement': date_of_settlement,
                    'status_of_settlement': status_of_settlement,
                    'exchange_trade_id': exchange_trade_id,
                })
        
        print(f"Parsed {len(executions)} SETTLED executions from {filepath}")
        
    except FileNotFoundError:
        print(f"Warning: {filepath} not found.")
        return None
    except Exception as e:
        print(f"Error parsing executions file: {e}")
        return None
    
    return executions if executions else None

def generate_trade_status():
    """Generate trade status based on distribution: 5% PENDING_SETTLEMENT, 93% SETTLED, 2% DISPUTED"""
    rand = random.random()
    if rand < 0.05:
        return 'PENDING_SETTLEMENT'
    elif rand < 0.98:  # 0.05 + 0.93
        return 'SETTLED'
    else:
        return 'DISPUTED'

def generate_trades(executions):
    """Generate trade records from settled executions"""
    trades = []
    trade_id = 1
    
    for execution in executions:
        # Generate trade status with specified distribution
        trade_status = generate_trade_status()
        
        # Generate trade date shortly after settlement date
        # Parse settlement date and add 0-2 days
        settlement_date = datetime.strptime(execution['date_of_settlement'], '%Y-%m-%d')
        trade_date = settlement_date + timedelta(days=random.randint(0, 2))
        
        trade = {
            'trade_id': trade_id,
            'execution_id': execution['execution_id'],
            'trade_price': execution['price_of_execution'],
            'shares': execution['quantity_filled'],
            'trade_status': trade_status,
            'trade_date': trade_date.strftime('%Y-%m-%d'),
        }
        
        trades.append(trade)
        trade_id += 1
    
    return trades

def format_trades_sql(trades):
    """Format trades as SQL INSERT statements"""
    sql_lines = [
        "-- filepath: c:\\Users\\Administrator\\Downloads\\data_generator\\trades_insert.sql",
        "-- Trades generated by trades_generator.py",
        "-- Execute this file in PostgreSQL to populate the Trades table",
        f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"-- Total records: {len(trades)}",
        "-- Table: Trades (Trade_ID, Execution_ID, Trade_Price, Shares, Trade_Status, Trade_Date)",
        ""
    ]
    
    for trade in trades:
        sql = f"INSERT INTO Trades (Trade_ID, Execution_ID, Trade_Price, Shares, Trade_Status, Trade_Date) VALUES ({trade['trade_id']}, {trade['execution_id']}, {trade['trade_price']}, {trade['shares']}, '{trade['trade_status']}', '{trade['trade_date']}');"
        sql_lines.append(sql)
    
    return "\n".join(sql_lines)

if __name__ == "__main__":
    # Parse input file
    executions_file = "executions_insert.sql"
    
    print("Parsing executions file...")
    executions = parse_executions_file(executions_file)
    
    if executions is None:
        print("Error: Failed to parse executions file")
        exit(1)
    
    print(f"\nStarting trade generation...")
    print(f"SETTLED Executions: {len(executions)}")
    
    # Generate trades
    trades = generate_trades(executions)
    
    # Format as SQL
    sql_output = format_trades_sql(trades)
    
    # Write to file
    output_path = "trades_insert.sql"
    with open(output_path, 'w') as f:
        f.write(sql_output)
    
    # Calculate and display status distribution
    pending = sum(1 for t in trades if t['trade_status'] == 'PENDING_SETTLEMENT')
    settled = sum(1 for t in trades if t['trade_status'] == 'SETTLED')
    disputed = sum(1 for t in trades if t['trade_status'] == 'DISPUTED')
    
    print(f"\nGenerated {len(trades)} trades")
    print(f"Trade Status Distribution:")
    print(f"  PENDING_SETTLEMENT: {pending} ({pending/len(trades)*100:.1f}%)")
    print(f"  SETTLED: {settled} ({settled/len(trades)*100:.1f}%)")
    print(f"  DISPUTED: {disputed} ({disputed/len(trades)*100:.1f}%)")
    print(f"Output written to {output_path}")
