from pathlib import Path
import random
import re

# Read user_ids from users_insert.sql
users_file = Path(__file__).parent / "users_insert.sql"
user_ids = []
with open(users_file, "r") as f:
    for line in f:
        match = re.search(r"VALUES \((\d+),", line)
        if match:
            user_ids.append(int(match.group(1)))

# Read role_ids from roles_insert.sql
roles_file = Path(__file__).parent / "roles_insert.sql"
role_ids = []
with open(roles_file, "r") as f:
    for line in f:
        match = re.search(r"VALUES \((\d+),", line)
        if match:
            role_ids.append(int(match.group(1)))

# Validate we have both files
if not user_ids or not role_ids:
    print("Error: Could not read users_insert.sql or roles_insert.sql")
    exit(1)

num_users = len(user_ids)
num_admin_users = random.randint(int(num_users * 0.04), int(num_users * 0.06))
admin_user_ids = set(random.sample(user_ids, num_admin_users))

output_path = Path(__file__).parent / "user_roles_insert.sql"
with open(output_path, "w") as f:
    f.write("-- User-Role mappings generated by user_roles_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the User_Roles table\n")
    f.write("-- Composite PK: (user_id, role_id)\n")
    f.write("-- Users have either CLIENT or ADMIN role (mutually exclusive)\n\n")
    
    # Assign CLIENT role to non-admin users
    for user_id in user_ids:
        if user_id not in admin_user_ids:
            f.write(f"INSERT INTO User_Roles (user_id, role_id) VALUES ({user_id}, {role_ids[0]});\n")
    
    f.write(f"\n-- Admin users get ADMIN role only (role_id={role_ids[1]})\n")
    
    # Assign ADMIN role to selected users only
    for user_id in admin_user_ids:
        f.write(f"INSERT INTO User_Roles (user_id, role_id) VALUES ({user_id}, {role_ids[1]});\n")

print(f"Generated user-role mappings from existing SQL files:")
print(f"- Read {num_users} user records from {users_file.name}")
print(f"- Read {len(role_ids)} roles from {roles_file.name}")
print(f"- {num_users - num_admin_users} users mapped to CLIENT role (role_id={role_ids[0]})")
print(f"- {num_admin_users} users mapped to ADMIN role (role_id={role_ids[1]})")
print(f"- Total rows: {num_users}")
print(f"- Composite PK: (user_id, role_id)")
print(f"- Saved to {output_path}")
