from faker import Faker
import random
from pathlib import Path

fake = Faker()

# Generate user records
num_users = 1000

users = []
for user_id in range(1, num_users + 1):
    # Status: 95% ACTIVE, 5% split among INACTIVE/SUSPENDED/LOCKED
    status_rand = random.random()
    if status_rand < 0.95:
        status = "ACTIVE"
    else:
        status = random.choice(["INACTIVE", "SUSPENDED", "LOCKED"])
    
    # Blacklisted: 3% chance of Y, 97% chance of N
    is_blacklisted = "Y" if random.random() < 0.03 else "N"
    
    user = {
        "user_id": user_id,
        "name": fake.name(),
        "email": fake.unique.email(),
        "password": fake.password(length=12, special_chars=True, digits=True, upper_case=True, lower_case=True),
        "created_date": fake.date_between(start_date="-2y", end_date="today"),
        "status": status,
        "is_blacklisted": is_blacklisted
    }
    users.append(user)

# Write to SQL file
output_path = Path(__file__).parent / "users_insert.sql"
with open(output_path, "w") as f:
    f.write("-- User records generated by user_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Users table\n\n")
    for user in users:
        # Escape single quotes in string values for SQL
        name = user["name"].replace("'", "''")
        email = user["email"].replace("'", "''")
        password = user["password"].replace("'", "''")
        
        sql = f"INSERT INTO Users (user_id, name, email, password, created_date, status, is_blacklisted) VALUES ({user['user_id']}, '{name}', '{email}', '{password}', '{user['created_date']}', '{user['status']}', '{user['is_blacklisted']}');\n"
        f.write(sql)

print(f"Generated {num_users} user records and saved to {output_path}")
print(f"Sample record: {users[0]}")