from faker import Faker
import random
from pathlib import Path
from datetime import datetime, timedelta

fake = Faker()

# Generate user records
num_users = 1000

users = []
for user_id in range(1, num_users + 1):
    # Status: 95% ACTIVE, 5% SUSPENDED
    status_rand = random.random()
    if status_rand < 0.95:
        status = "ACTIVE"
    else:
        status = "SUSPENDED"
    
    # Role assignment: 95% CLIENT (1), 5% ADMIN (2)
    role_rand = random.random()
    if role_rand < 0.95:
        role_id = 1  # CLIENT
    else:
        role_id = 2  # ADMIN
    
    # Generate timestamp with date and time
    base_date = datetime.now() - timedelta(days=730)  # 2 years ago
    days_ago = random.randint(0, 730)
    created_date = base_date + timedelta(days=days_ago, hours=random.randint(0, 23), minutes=random.randint(0, 59), seconds=random.randint(0, 59))
    
    user = {
        "user_id": user_id,
        "name": fake.name(),
        "email": fake.unique.email(),
        "password_hash": fake.password(length=60, special_chars=True, digits=True, upper_case=True, lower_case=True),
        "created_date": created_date,
        "status": status,
        "role_id": role_id
    }
    users.append(user)

# Write to SQL file
data_folder = Path(__file__).parent.parent / "data"
output_path = data_folder / "users_insert.sql"
with open(output_path, "w") as f:
    f.write("-- User records generated by user_generation.py\n")
    f.write("-- Execute this file in PostgreSQL to populate the Users table\n")
    f.write("-- Role_ID: 1=CLIENT (95%), 2=ADMIN (5%)\n\n")
    for user in users:
        # Escape single quotes in string values for SQL
        name = user["name"].replace("'", "''")
        email = user["email"].replace("'", "''")
        password_hash = user["password_hash"].replace("'", "''")
        
        created_date_str = user['created_date'].strftime('%Y-%m-%d %H:%M:%S')
        sql = f"INSERT INTO Users (User_ID, Name, Email, Password_Hash, Created_Date, Status, Role_ID) VALUES ({user['user_id']}, '{name}', '{email}', '{password_hash}', '{created_date_str}', '{user['status']}', {user['role_id']});\n"
        f.write(sql)

print(f"Generated {num_users} user records and saved to {output_path}")
print(f"- {int(num_users * 0.95)} CLIENT users (Role_ID=1)")
print(f"- {int(num_users * 0.05)} ADMIN users (Role_ID=2)")
print(f"Sample record: {users[0]}")
