DROP TABLE IF EXISTS FACT_DISPUTES;
DROP TABLE IF EXISTS FACT_TRANSACTIONS;
DROP TABLE IF EXISTS FACT_TRADES;
DROP TABLE IF EXISTS DIM_SECURITY;
DROP TABLE IF EXISTS DIM_ACCOUNT;
DROP TABLE IF EXISTS DIM_USER;
DROP TABLE IF EXISTS DIM_DATE;

CREATE TABLE DIM_DATE (
    Date_Key INTEGER PRIMARY KEY,
    Full_Date DATE NOT NULL UNIQUE,
    Day_Number SMALLINT NOT NULL,
    Day_Name VARCHAR(10) NOT NULL,
    Week_Number SMALLINT NOT NULL,
    Month_Number SMALLINT NOT NULL,
    Month_Name VARCHAR(15) NOT NULL,
    Quarter_Number SMALLINT NOT NULL,
    Year_Number SMALLINT NOT NULL,
    Is_Weekend BOOLEAN NOT NULL
);

CREATE TABLE DIM_USER (
    User_Key BIGSERIAL PRIMARY KEY,
    User_ID BIGINT NOT NULL UNIQUE,
    User_Name VARCHAR(100) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Is_Blacklisted CHAR(1) NOT NULL
);

CREATE TABLE DIM_ACCOUNT (
    Account_Key BIGSERIAL PRIMARY KEY,
    Account_ID BIGINT NOT NULL UNIQUE,
    User_Key BIGINT NOT NULL,
    Account_Status VARCHAR(20) NOT NULL,
    Created_Date DATE NOT NULL,
    FOREIGN KEY (User_Key)
        REFERENCES DIM_USER(User_Key)
);

CREATE TABLE DIM_SECURITY (
    Security_Key BIGSERIAL PRIMARY KEY,
    Security_ID BIGINT NOT NULL UNIQUE,
    Ticker VARCHAR(20) NOT NULL,
    Company_Name VARCHAR(255) NOT NULL,
    Sector VARCHAR(100) NOT NULL,
    Asset_Type VARCHAR(50) NOT NULL,
    Exchange VARCHAR(50) NOT NULL,
    Security_Status VARCHAR(20) NOT NULL
);

CREATE TABLE FACT_TRADES (
    Trade_Fact_Key BIGSERIAL PRIMARY KEY,
    Trade_ID BIGINT NOT NULL,
    Date_Key INTEGER NOT NULL,
    User_Key BIGINT NOT NULL,
    Account_Key BIGINT NOT NULL,
    Security_Key BIGINT NOT NULL,
    Trade_Type CHAR(1) NOT NULL,
    Shares NUMERIC(18,4) NOT NULL,
    Trade_Price NUMERIC(18,4) NOT NULL,
    Trade_Value NUMERIC(18,4) NOT NULL,
    FOREIGN KEY (Date_Key)
        REFERENCES DIM_DATE(Date_Key),
    FOREIGN KEY (User_Key)
        REFERENCES DIM_USER(User_Key),
    FOREIGN KEY (Account_Key)
        REFERENCES DIM_ACCOUNT(Account_Key),
    FOREIGN KEY (Security_Key)
        REFERENCES DIM_SECURITY(Security_Key)
);

CREATE TABLE FACT_TRANSACTIONS (
    Transaction_Fact_Key BIGSERIAL PRIMARY KEY,
    Transaction_ID BIGINT NOT NULL,
    Date_Key INTEGER NOT NULL,
    User_Key BIGINT NOT NULL,
    Account_Key BIGINT NOT NULL,
    Transaction_Type VARCHAR(20) NOT NULL,
    Transaction_Amount NUMERIC(18,4) NOT NULL,
    FOREIGN KEY (Date_Key)
        REFERENCES DIM_DATE(Date_Key),
    FOREIGN KEY (User_Key)
        REFERENCES DIM_USER(User_Key),
    FOREIGN KEY (Account_Key)
        REFERENCES DIM_ACCOUNT(Account_Key)
);

CREATE TABLE FACT_DISPUTES (
    Dispute_Fact_Key BIGSERIAL PRIMARY KEY,
    Dispute_ID BIGINT NOT NULL,
    Date_Key INTEGER NOT NULL,
    User_Key BIGINT NOT NULL,
    Account_Key BIGINT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (Date_Key)
        REFERENCES DIM_DATE(Date_Key),
    FOREIGN KEY (User_Key)
        REFERENCES DIM_USER(User_Key),
    FOREIGN KEY (Account_Key)
        REFERENCES DIM_ACCOUNT(Account_Key)
);
