-- Roles reference data generated by roles_generation.py
-- Execute this file in PostgreSQL to populate the Roles table
-- These are static reference roles used by the platform

INSERT INTO Roles (Role_ID, Name) VALUES (1, 'CLIENT');
INSERT INTO Roles (Role_ID, Name) VALUES (2, 'ADMIN');
